### ISSUE TITLE
[São Paulo - SP] FCAMARA - Desenvolvedor Java/Node Pleno/Sênior.

### ISSUE THREAD

**Issue by baixada** [baixada/Vagas#2]
![LogoFcamara](http://blog.fcamara.com.br/wp-content/uploads/2016/02/Logotipo-Horizontal-FCamara-2015-e1455123821994.png)

Se você busca crescimento constante, não gosta de zonas de conforto e acredita que os maiores desafios são os melhores, a FCamara é seu lugar!
 
Estamos montando uma Heath Tech Squad para um super desafio e vamos precisar de Desenvolvedores Java Sênior Full Stack que atendam os seguintes requisitos: Spring, Springbot, Hibernate, Node.js, Vue.js, AWS ou Azure, Docker.
 
Vindo para a FCamara você terá a oportunidade de fazer parte do time de Inovação, uma equipe interdisciplinar, dinâmica e engajada em surpreender nossos clientes e dar novas soluções para problemas diversos.

Envie seu CV para: <mayara.miranda@fcamara.com.br>

**Comment by DavideCarvalho** [comment]
Podem falar sobre o salário para Sênior?
